version: "3.9"

services:

  prometheus:

    image: prom/prometheus

    ports:

      - "9090:9090"

    volumes:

      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

      - ../monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml

  grafana:

    image: grafana/grafana

    ports:

      - "3000:3000"

  simulator:

    build:

      context: ..

      dockerfile: docker/Dockerfile.lambda
